global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # - targets: ['host.docker.internal:8083']  # For Mac/Windows
      # For Linux, use the Docker network gateway IP instead of host.docker.internal
      - targets: ['192.168.0.3:8083']  # Docker default gateway IP

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
